### ISSUE TITLE
SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by dahartigan** [interlark/123tv-iptv#1]
Hi @interlark - Thank you very much for your work!

I have tried to install this with pip and when I run 123tv-iptv I get an error:

```
  File "/usr/local/bin/123tv-iptv", line 5
    from 123tv_iptv import main
           ^
SyntaxError: invalid decimal literal
```

Thank you again for your excellent work (with this and the ustvgo repo!)

EDIT:  If I clone the repo and run the script manually, it works.  It seems to be isolated to the script in /usr/local/bin/ that pip installs it to.  Not significant to me, but may be a barrier for others.

**Comment by interlark** [comment]
@dahartigan, Thank you for the feedback. In the next release I'm gonna fix auth key rotation and this `wheel` related issue.

**Comment by dahartigan** [comment]
Thank you @interlark - I can't express enough how much I appreciate this :)

**Comment by dahartigan** [comment]
Fixed, closing. Thanks again!
