### ISSUE TITLE
Rest of channels

### ISSUE THREAD

**Issue by DeltaSr95** [interlark/123tv-iptv#3]
Is there any way to extract the other channels from the site to put into the channels.json file manually?  Examples, Animal Planet, TBS, CBS, etc...

**Comment by interlark** [comment]
The rest of the channels need a bit different treatment, I could add them later.

**Comment by D3adlyRocket** [comment]
Hey DeltaSr95
Any chance you can update the Distro TV Epg and add 2 more channels?
