### ISSUE TITLE
Entered Playlist but not finding any channels

### ISSUE THREAD

**Issue by Eddison242** [interlark/123tv-iptv#4]
Im new user but been on here a while in reference to kodi but, i entered the epg and Playlist but its mot finding any channels.  Is it 123tv-iptv instead of 123tv?

**Comment by interlark** [comment]
I just ran the following command
```
pip install 123tv-iptv
```
and then ran
```
123tv-iptv
```
The server gave me the next output
```
10:51:37 :: INFO :: Serving http://127.0.0.1:6464/123tv.m3u8
10:51:37 :: INFO :: Serving http://127.0.0.1:6464/tvguide.xml
10:51:37 :: INFO :: Serving http://10.10.8.1:6464/123tv.m3u8
10:51:37 :: INFO :: Serving http://10.10.8.1:6464/tvguide.xml
10:51:37 :: INFO :: Serving http://172.17.0.1:6464/123tv.m3u8
10:51:37 :: INFO :: Serving http://172.17.0.1:6464/tvguide.xml
...
```
Same server you can ran with [GUI](https://github.com/interlark/123tv-iptv/releases/latest) and `Docker`:
  ```bash
  docker run -d --name=123tv-iptv -p 6464:6464 --restart unless-stopped ghcr.io/interlark/123tv-iptv:latest
  ```

If you're inexperienced user, you better get GUI app, run it and click `Start` button.
It works like a charm :)

**Comment by Eddison242** [comment]
Sorry, I was trying to put it in as a m3u playlist on kodi thats why I asked . And also I was trying to use your server address because I'm not too experienced with these things. I noticed that this is a software though.
